[package]
name = "hello-wasm"
version = "0.1.0"
authors = "d"
description = "d"
license = "MIT/Apache-2.0"
repository = "d"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
